### ISSUE TITLE
This app requires features that aren't available - PS4

### ISSUE THREAD

**Issue by coreylfarrow** [kevcenteno/BallPlex.bundle#9]
I haven't been able to watch streams on my PS4 for a couple weeks now, so I decided to check if there was an update. Found this, updated and now receive this error. NoRTMP doesn't seem to help. Also, updated my Plex Server, but still same error. I've entered account credentials and tried all combos of options. For installation, I just replaced the existing Ballplex.bundle - hopefully that's sufficient.

**Comment by kevcenteno** [comment]
Nortmp should resolve this....  Try deleting the existing ballplex.bundle folder before reinstalling the nortmp version

**Comment by coreylfarrow** [comment]
Tried deleting the actual .bundle file and also removing the app via the Plex Media Server, neither seemed to do the trick.

**Comment by kevcenteno** [comment]
To confirm, you are using the nortmp version, right? I don't have a ps4, so
I unfortunately can't test this for you... But other uses have confirmed
that all of this works.

**Comment by kevcenteno** [comment]
https://github.com/kevcenteno/ballplex.bundle/tree/noRTMP

**Comment by coreylfarrow** [comment]
Sorry, I'm not super familar with Github and was just pulling the zip from the link in the readme still. Maybe change that link if possible? Anyways, I'm able to browse now, but still not able to view games - as I haven't for a couple weeks now. I just get "There was a problem playing..." or spinning circle. Everything works fine via browser, just now PS4. Sorry, I know that's not super specific, is there any log info that'd be more helpful?
